### PR TITLE
Add method to get list of kits

### PR DESCRIPTION
**Pull request by dentmaged**
Used by https://github.com/bolt-rip/kiteditor

### CODE REVIEW

**Comment by KingOfSquares** [comment]
@dentmaged that project seems to be private. If you want to show usage you need to copy some code or something.

Furthermore, why are you exposing this when you can just fetch it from the `MatchFeatureContext`?

**Comment by KingOfSquares** [comment]
Actually, reading through the source code I see that kits are never put into the context. I think this should be the approach instead of exposing the kits in the way this PR currently does, though.

**Comment by Electroid** [comment]
I think using `MatchFeatureContext` would be the proper fix.

**Comment by Pablete1234** [comment]
You cannot use `MatchFeatureContext` as kits are not stored in it, kits are not a feature to start with.

To add further, where kits ARE added is either `KitContext` for legacy maps or `FeatureDefinitionContext` inside MapFactory, but that is scoped to parse-time, and discarded afterwards

**Comment by Pablete1234** [comment]
@Electroid could you re-review?

**Pull request closed without merging**
