### PR TITLE
Bump ViaVersion to 4.0.1

### PR DESCRIPTION
**Pull request by applenick**
This PR updates ViaVersion from 3.0.2 -> 4.0.1

Signed-off-by: applenick <applenick@users.noreply.github.com>

### CODE REVIEW

**Comment by calcastor** [comment]
ViaVersion has a legacy API that redirects any references to `us.myles.ViaVersion` to the new API. Maybe it would be best to keep that to allow servers to use older versions of ViaVersion et al. if necessary, given bugs such as dropped items showing as stone for all 1.7 users with upstream ViaRewind for instance?

**Comment by applenick** [comment]
> ViaVersion has a legacy API that redirects any references to `us.myles.ViaVersion` to the new API. Maybe it would be best to keep that to allow servers to use older versions of ViaVersion et al. if necessary, given bugs such as dropped items showing as stone for all 1.7 users with upstream ViaRewind for instance?

Oh shoot! Is that a thing? 

This was mainly to fix the compile error in #904

**Comment by applenick** [comment]
Thanks @calcastor, found the api-legacy package! That was neat to learn. All fixed now 👍

**Comment by calcastor** [comment]
> > ViaVersion has a legacy API that redirects any references to `us.myles.ViaVersion` to the new API. Maybe it would be best to keep that to allow servers to use older versions of ViaVersion et al. if necessary, given bugs such as dropped items showing as stone for all 1.7 users with upstream ViaRewind for instance?
> 
> Oh shoot! Is that a thing?
> 
> This was mainly to fix the compile error in #904

That is my understanding of what [this](https://github.com/ViaVersion/ViaVersion/blob/8fb51bf3b7d1106c9aafe2344556eb2b82207061/api-legacy/src/main/java/us/myles/ViaVersion/api/Via.java) does at least. I've been modifying the pom.xml to reference the latest version of ViaVersion when I build locally, but haven't been updating ViaUtils and it has seemed to work 100% as intended. I'd assume that updating ViaUtils to not use the legacy API might break it when using older versions of ViaVersion. 

edit: see above I guess I missed a comment when writing this out haha!

**Pull request merged**
