### PR TITLE
Added option to click a link to download SportsPaper.

### PR DESCRIPTION
**Pull request by benrobson**
I've added an option for users to just click a link to download SportsPaper, in the case that they don't know how to use bash (for the novice user they wouldn't know).

Signed off by Ben Robson

### CODE REVIEW

**Comment by KingOfSquares** [comment]
Good idea! To get DCO to pass you have to sign off your commits :)

**Comment by benrobson** [comment]
So I edited my original commit message and added a sign-off, should update eventually?

**Comment by benrobson** [comment]
Well getting DCO to sign off the commit took a while but I think I got it.

**Comment by Electroid** [comment]
I updated the README during last release.

**Pull request closed without merging**
