### PR TITLE
Switch javax nullness with checkerframework

### PR DESCRIPTION
**Pull request by KingOfSquares**
Necessary for #54
Signed-off-by: KingSimon <19822231+KingOfSquares@users.noreply.github.com>

### CODE REVIEW

**Review by Pablete1234 — COMMENTED** [review]
Why not just use javax annotations? 
https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api

Modifying every import to switch to checkerframework isn't needed

**Comment by KingOfSquares** [comment]
> Why not just use javax annotations?
> https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api
> 
> Modifying every import to switch to checkerframework isn't needed

My idea was that if we used checkerframework we didn't need to bring in another dependency, since adventure already ships checkerframework

**Comment by Pablete1234** [comment]
> > Why not just use javax annotations?
> > https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api
> > Modifying every import to switch to checkerframework isn't needed
> 
> My idea was that if we used checkerframework we didn't need to bring in another dependency, since adventure already ships checkerframework

Java annotations like notnull are (usually) not kept at runtime so it won't really save anything.
The javax annoations are pretty standard and most things are compatible with it

**Comment by Electroid** [comment]
I'd rather stick with `javax`

**Pull request closed without merging**
